# LLM智能体配置文件

# 默认模型配置
default_model: "claude-sonnet-4-20250514"

# 模型配置
models:
  # Claude模型
  claude-sonnet-4-20250514:
    name: "claude-sonnet-4-20250514"
    strategy: "balanced"
    temperature: 0.7
    max_tokens: 8192
    description: "Claude Sonnet 4 - 平衡策略，适合大多数任务"

  claude-3-opus:
    name: "claude-3-opus"
    strategy: "conservative"
    temperature: 0.5
    max_tokens: 8192
    description: "Claude 3 Opus - 保守策略，适合复杂任务"

  claude-3-sonnet:
    name: "claude-3-sonnet"
    strategy: "balanced"
    temperature: 0.7
    max_tokens: 8192
    description: "Claude 3 Sonnet - 平衡策略，性价比高"

  claude-3-haiku:
    name: "claude-3-haiku"
    strategy: "aggressive"
    temperature: 0.9
    max_tokens: 4096
    description: "Claude 3 Haiku - 激进策略，快速响应"

  # OpenAI模型
  gpt-4:
    name: "gpt-4"
    strategy: "balanced"
    temperature: 0.7
    max_tokens: 8192
    description: "GPT-4 - 平衡策略，功能强大"

  gpt-4o-mini:
    name: "gpt-4o-mini"
    strategy: "aggressive"
    temperature: 0.8
    max_tokens: 4096
    description: "GPT-4o Mini - 激进策略，快速响应"

  gpt-3.5-turbo:
    name: "gpt-3.5-turbo"
    strategy: "aggressive"
    temperature: 0.9
    max_tokens: 4096
    description: "GPT-3.5 Turbo - 激进策略，成本低"

# 策略配置
strategies:
  aggressive:
    description: "激进策略 - 快速决策，优先价格"
    default_action: "add_to_cart"
    temperature: 0.9

  balanced:
    description: "平衡策略 - 平衡价格和质量"
    default_action: "search_flights"
    temperature: 0.7

  conservative:
    description: "保守策略 - 优先质量，仔细评估"
    default_action: "filter_results"
    temperature: 0.5

# 环境配置
environment:
  max_episodes: 100
  max_steps_per_episode: 50
  timeout_seconds: 300

# 日志配置
logging:
  level: "INFO"
  format: "%(asctime)s - %(levelname)s - %(message)s"
  file: "logs/llm_agent.log"
