# 研究环境配置 - 最大化观测和分析能力

observation:
  enabled: true
  
  web_dashboard:
    enabled: true
    port: 5000
    auto_open_browser: false
  
  console_reporting:
    enabled: true
    interval_seconds: 5
    verbose: true
    show_skill_details: true
  
  visualization:
    real_time_plots: true
    trajectory_analysis: true
    skill_evolution_plots: true
    save_plots: true
    plot_update_interval: 1
  
  reporting:
    auto_generate: true
    output_dir: "logs/research_reports"
    formats: ["txt", "json", "html"]
    include_detailed_trajectories: true

monitoring:
  episode_metrics:
    - "success_rate"
    - "avg_reward"
    - "avg_steps"
    - "skill_usage_rate"
    - "error_rate"
  
  skill_metrics:
    - "learning_rate"
    - "usage_frequency"
    - "success_rate"
    - "improvement_rate"
  
  real_time_threshold: 0.05
  sliding_window_size: 10
  stats_report_frequency: 20

storage:
  event_queue_size: 20000
  trajectory_retention:
    max_episodes_per_experiment: 2000
    compress_old_trajectories: false
  
  skill_retention:
    max_skill_history: 10000
    auto_cleanup: false

performance:
  event_batch_size: 50
  max_update_frequency: 20
  max_memory_mb: 1024

alerts:
  enabled: true
  performance_alerts:
    low_success_rate_threshold: 0.15
    high_error_rate_threshold: 0.2
    slow_learning_threshold: 0.02
  system_alerts:
    memory_threshold_mb: 800
    queue_full_threshold: 0.9