# 最小化配置 - 适合快速测试

observation:
  enabled: true
  
  web_dashboard:
    enabled: true
    port: 5000
  
  console_reporting:
    enabled: true
    interval_seconds: 15
  
  visualization:
    real_time_plots: false  # 禁用实时图表以提高性能
    trajectory_analysis: false
  
  reporting:
    auto_generate: true
    output_dir: "logs/minimal_reports"

monitoring:
  episode_metrics:
    - "success_rate"
    - "avg_reward"
  
  real_time_threshold: 0.5  # 较宽松的实时性要求

performance:
  event_batch_size: 50
  max_update_frequency: 5