# 生产环境配置 - 优化性能和稳定性

observation:
  enabled: true
  
  web_dashboard:
    enabled: true
    port: 8080
    host: "0.0.0.0"
  
  console_reporting:
    enabled: true
    interval_seconds: 30
    verbose: false
  
  visualization:
    real_time_plots: false
    trajectory_analysis: false
    save_plots: true
  
  reporting:
    auto_generate: true
    output_dir: "logs/production_reports"
    formats: ["json", "txt"]
    include_detailed_trajectories: false

monitoring:
  episode_metrics:
    - "success_rate"
    - "avg_reward"
    - "avg_steps"
    - "error_rate"
  
  skill_metrics:
    - "usage_frequency"
    - "success_rate"
  
  real_time_threshold: 1.0
  sliding_window_size: 50
  stats_report_frequency: 100

storage:
  event_queue_size: 5000
  trajectory_retention:
    max_episodes_per_experiment: 500
    compress_old_trajectories: true
  
  skill_retention:
    max_skill_history: 1000
    auto_cleanup: true

performance:
  event_batch_size: 200
  max_update_frequency: 2
  max_memory_mb: 256

alerts:
  enabled: true
  performance_alerts:
    low_success_rate_threshold: 0.05
    high_error_rate_threshold: 0.4
  system_alerts:
    memory_threshold_mb: 200
    queue_full_threshold: 0.8